# Generated by Django 3.1.4 on 2022-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_coverpic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coverpic',
            field=models.ImageField(blank=True, upload_to='post'),
        ),
    ]
